[package]
name = "bevy_inventory_system"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", features = ["dynamic_linking"] }
bevy_flat_arrays = { git = "https://github.com/DirkChristianBecker/bevy_flat_arrays.git" }

rand = { version = "*" }